# Generated by Django 4.2.11 on 2024-04-30 06:49

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
