# Generated by Django 4.2.11 on 2024-05-11 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_remove_product_model_product_user_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
