# Generated by Django 4.2.11 on 2024-05-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0009_cart_checkout_product_review_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
    ]
