# Generated by Django 4.2.11 on 2024-05-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0011_rename_user_checkout_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
    ]
